name: Cypress Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install    # <-- changed from `npm ci` to `npm install`

      # Step 4: Run Cypress tests
      - name: Run Cypress Tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          headed: false

# upload videos (optional)
      - name: Upload Cypress Videos
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos

     # upload screenshots if test fails
      - name: Upload Cypress Screenshots
        if: failure()  # only upload if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
